site_name: Kevin Muscara
nav:
  - Home: index.md
  - Projects:
      - Smarter JSON Handling for HTMX: projects/smarter-json-handling-for-htmx.md
      - Suicidal Ideation Classifier: https://github.com/kevinmuscara/suicidal-ideation
      - Graphing Pupil Movement: https://github.com/kevinmuscara/mediapipe-pupil
  - Conferences:
      - BrainStorm 2026: https://brainstormk20.com/sandusky
      - STLP 2022: conferences/stlp22.md
  - Experience:
      - West Clermont School District: https://westcler.org
      - Northern Kentucky University: https://nku.edu
      - Jessamine County Schools: https://jessamine.k12.ky.us
theme:
  name: terminal
  palette: sans
  features:
    - navigation.side.toc.hide


markdown_extensions:
  - pymdownx.superfences         # required extension
  - pymdownx.highlight:
      use_pygments: true         # use pygments library    
      pygments_style: default    # use 'default' style
      noclasses: true            # update HTML style attr
  - pymdownx.inlinehilite        # style inline code
extra_javascript:
  - javascripts/remove_watermark.js